# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0012_auto_20180926_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('widget_key', models.CharField(choices=[('pvobstacle', 'Obstacles'), ('pvtech', 'Thechnology (photovoltaic)'), ('pvnum', 'Number of Panels (photovoltaic)'), ('pvcons', 'Consumption (photovoltaic)'), ('pvauto', 'Autonomy (photovoltaic)'), ('pvvat', 'VAT (photovoltaic)'), ('pvloan', 'Loan (photovoltaic)'), ('thsys', 'System (thermal)'), ('thcons', 'Consumption (thermal)'), ('thgrant', 'Grant (thermal)'), ('thvat', 'VAT (thermal)'), ('thloan', 'Loan (thermal)')], max_length=12)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjust_description', to='api.MessageRecord')),
            ],
        ),
        migrations.CreateModel(
            name='SolarSim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current', models.BooleanField(default=False)),
                ('max_power', models.FloatField()),
                ('co2_emissions_by_kwh', models.FloatField()),
                ('energetic_cost_factor_belgium', models.FloatField()),
                ('energetic_cost_factor_europe', models.FloatField()),
                ('energetic_cost_factor_china', models.FloatField()),
                ('thermic_production', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
