# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_auto_20180926_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsim',
            name='name',
            field=models.CharField(default='(none)', max_length=128),
        ),
        migrations.AlterField(
            model_name='solarsim',
            name='co2_emissions_by_kwh',
            field=models.FloatField(default=0.456, help_text='CO2 emissions by kWh of electric energy, in kg/kWh'),
        ),
    ]
