# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_auto_20181010_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsim',
            name='medium_solar_productivity',
            field=models.FloatField(default=940, help_text='Medium solar productivity for a roof in Bruxelles, in         kWh/m².an'),
        ),
    ]
