# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_solarsim_medium_solar_productivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsim',
            name='battery_cost',
            field=models.FloatField(default=7000, help_text='Cost of a home battery, in €'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='obstacle_area_chimneySmoke',
            field=models.FloatField(default=0.8719, help_text='Average obstacle area for a chimney, in m²'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='obstacle_area_dormerWindow',
            field=models.FloatField(default=5.339, help_text='Average obstacle area for a dormer window, in m²'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='obstacle_area_existingSolarPannel',
            field=models.FloatField(default=36.05, help_text='Average obstacle area for a existing solar panel         installation, in m²'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='obstacle_area_flatRoofWindow',
            field=models.FloatField(default=4.192, help_text='Average obstacle area for a flat roof window, in m²'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='obstacle_area_lift',
            field=models.FloatField(default=10.93, help_text='Average obstacle area for a lift on a flat roof, in m²'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='obstacle_area_terraceInUse',
            field=models.FloatField(default=26.09, help_text='Average obstacle area for a terrace, in m²'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='obstacle_area_velux',
            field=models.FloatField(default=1.409, help_text='Average obstacle area for a velux, in m²'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='obstacle_default_rate',
            field=models.FloatField(default=0.177, help_text='Default obstacle rate for a building'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='pvheater_cost',
            field=models.FloatField(default=1700, help_text='Cost of a PV heater, in €'),
        ),
        migrations.AlterField(
            model_name='solarsim',
            name='low_productivity_limit',
            field=models.FloatField(default=722.5, help_text='Low limit for roof productivity (kWh/kWc.m²). No         photovoltaic production is considered for roofs with a productivity         below this limit.'),
        ),
        migrations.AlterField(
            model_name='solarsim',
            name='medium_solar_productivity',
            field=models.FloatField(default=831.25, help_text='Medium solar productivity for a roof in Bruxelles, in         kWh/m².an'),
        ),
    ]
