# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_solarsim_lost_space_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsim',
            name='cv_rate_high_power',
            field=models.FloatField(default=1.8182, help_text='Rate of Certificat Vert for high power installation, in         CV/MWh'),
        ),
        migrations.AlterField(
            model_name='solarsim',
            name='cv_rate_low_power',
            field=models.FloatField(default=2.4, help_text='Rate of Certificat Vert for low power installation, in         CV/MWh'),
        ),
    ]
