# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0008_solar_sim_alter_cv_rate_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarsim',
            name='annual_consumption_base',
        ),
        migrations.RemoveField(
            model_name='solarsim',
            name='washing_machine_factor',
        ),
        migrations.AddField(
            model_name='solarsim',
            name='electric_water_heater_min_consumption',
            field=models.FloatField(default=1000, help_text='Minimal supplementary electricity consumption for electric         production of hot water with a pv heater, in kWh/year'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='energy_sobriety_factor',
            field=models.FloatField(default=0.8, help_text='Change factor when user choose energy sobriety as behaviour'),
        ),
        migrations.AlterField(
            model_name='solarsim',
            name='electric_water_heater_factor',
            field=models.FloatField(default=1.46, help_text='Change factor for electric production of hot water with a         pv heater'),
        ),
    ]
