# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_add_autoconso_related_constants'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsim',
            name='cv_price',
            field=models.FloatField(default=85, help_text='Price of a certificat vert, in €'),
        ),
        migrations.AddField(
            model_name='solarsim',
            name='elec_selling_price',
            field=models.FloatField(default=0.03, help_text='Selling electricity price (for prosumers), in €/kWh'),
        ),
    ]
