# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import solar_loader.models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_solarsim_cv_rate_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsim',
            name='cv_rate_classes',
            field=models.TextField(default=solar_loader.models.cv_rate_classes_default, help_text='Classes of Certificat verts rate by installed power in kWc.         Each certificat vert rate (`cv_rate`) value is applied for the range of         installed power between its respective `lower_limit` and `upper_limit`         values. The larger (the last) `upper_limit` must be large enough to         apply in any situation (e.g., 9999999999 kWc).'),
        ),
    ]
